# Generated by Django 3.1.4 on 2020-12-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
    ]
